language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: dist
 on:
   branch: master

env:
  global:
    secure: e7hnDPYhU/pOekEoWaNFwTzbRQuqMEBVJK7oi9SY52zGKKisfp6MzzfF8YYS6F3WtwB4Sq/Fbk+GfNcxKyIEDk5l2QeC54tzUCgPsIz0D0PuQRlz48gYMixgHc32oSLWH3H3sNOv/7DflpDzYTned4M+nu7MRjzlhtWs5fkdWntUHFRGPfB1LOugjeaqI032rHP7ld1xFkCZkR+cjAqtUaHgK9CSpQEelDkfBfdrJ0VMLSSMNIp7nPaPD/A8201lwAKJKWqdgC/U97K6xpCQVLKyuFo9U/bfwvITd+2RdghXoqqH8MWn/aam3EEOnxEDi7ffwbCNqshCGjb3lNmdSrVRGHpV7BRINYTGqRmM+LzT/tCt4krD9FndsERmV5Ib2zS5ofU5iUyJf5+3es0ofAj5O7DpzOwn/0a6i6mRXtFwamCwqnjwVZWac4VB3zXkpJUQQXsF+9adsHv/x9rFFEdxm4eKEmQ8tSi8lHIHW8iGitWWfAFvYJWMFD101KZImBCTPJKnxg+w9vYBJ7nEgOOOVR+W90tsR82B1w8HAJFdWg1FKnkF7dA1HpzXARpcm+P0VXsiRYwt0NBwT1cdwz/PH+c84NMZGk5zFHAbrLSAI7DVLjyT1yF2kWSWpgBHyOBdBU4TMukQmnlaPQGsAVBzNZ5zwiVdhlpL3WgYQu8=
