language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: dist
 on:
   branch: master

env:
  global:
    secure: pF/EEM4PJ5h4mHB1akXyh45s8BcTrQz7OPhC12RiRlSx0bLddFWaVbk+RGMvVy9+zOTf0tFi6+FmjFyiTleqeo10GG+5CgNk5iKjhYcV2jR0FSqOvRW3VfvKlZeQJ09H94XG/Qph37e/RyafUpAllA8
Af1VpS9p4QH++LYCFe9mYjrIl/AUUbG7a34xx98s9wNL6LwIj777sjIyfWI2O/9hDa+Vvh/OXSq+NmND5ZeJwm4EXHIPfxDnno6yHxCWz7MOYDIWjW5Ak03mJozlz2Vpm45kXHysls3mm1N1PY/BIdzHkG+af/GZjG
itbKh/VtcSc7yJiO6C0IGQQn9eUeba0niazUi+6dgSN87AitTZcSyNoJm08Odz9eFbEijaXju8yQpzGwR4aDzsSBPlqacmeRNS2p7YZKT491ZA9OlmUGAm+OJIzpeCNONPHbqJ9aq5Tk8Kad1qtuUjVZ4nui9JSRz+
RCsHugVl+MKI5h9Kh4T8acDAcuNv704de7ZRoshx3HOs9t3O+rsIlQZE+8z7GstKOaPQ7LnUrNy1HVhaYxjSPiIVxFhI6Vxdc0mLhzZYxqbIYOx0UpORmL/fWSbFPdJBA/9SOog8EDV2SGTaKkcWWteL1wQINeyLSo
veRHYRqgg4Uq/F7lhHd4m9rjen6MO3qhW12M6DsENa9KdY=
